set(CMAKE_CROSSCOMPILING TRUE)
set(CMAKE_SYSTEM_PROCESSOR riscv64)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_CXX_COMPILER_ID GNU)
set(VENDOR unknown-)
set(MODE linux-gnu)

include(${CMAKE_CURRENT_LIST_DIR}/common.cmake)
